FROM ubuntu:20.04
RUN apt-get update  
RUN apt-get -y upgrade  
RUN apt-get install -yq apt-utils dialog 
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install -yq build-essential software-properties-common  
RUN apt-get update  
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN pip3 install --upgrade pip

RUN pip3 install jupyter

# # Add Tini. Tini operates as a process subreaper for jupyter. This prevents kernel crashes.
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]

#RUN mkdir /root/src/
#WORKDIR /root/src/
#COPY . .
#RUN pip3 install -r requirements.txt
